Allow calling standard completion function from custom one
yargs/yargs pull request #1855
Opened 2021-01-24 20:22 UTC by gardenappl

See #1013 

Based on work by @tkarls (https://github.com/yargs/yargs/issues/1013#issuecomment-346814408). This is my first time working with TypeScript so my solution might be a bit ugly.

One thing that worries me is that this API requires you to use callbacks. There is no good way to overload this function:

```ts
export type CompletionFunction =
  | SyncCompletionFunction
  | AsyncCompletionFunction
  | FallbackCompletionFunction;

interface SyncCompletionFunction {
  (current: string, argv: Arguments): string[] | Promise<string[]>;
}

interface AsyncCompletionFunction {
  (current: string, argv: Arguments, done: (completions: string[]) => any): any;
}

interface FallbackCompletionFunction {
  (
    current: string,
    argv: Arguments,
    defaultCompletion: () => any,
    done: (completions: string[]) => any
  ): any;
}
```

Each function takes 2, 3 or 4 arguments respectively.

One possible solution: since you're about to release a new major version, it might be OK to just remove the ability to use callbacks, in favor of Promises. So then the new API would look like this:

```ts
export type CompletionFunction =
  | LegacyCompletionFunction
  | FallbackCompletionFunction;

interface LegacyCompletionFunction {
  (current: string, argv: Arguments): string[] | Promise<string[]>;
}

interface FallbackCompletionFunction {
  (current: string, argv: Arguments, defaultCompletion: () => any): string[] | Promise<string[]> | void;
}
```

2021-02-15 20:30 UTC, bcoe requested changes
@gardenappl this is looking really solid to me. What jumps out at me the most is that we've collected enough logic in `completion.ts`, that I think we'd benefit from a tiny bit of refactoring.

2021-02-15 20:30 UTC, bcoe commented on lib/completion.ts
> +      const handlers = command.getCommandHandlers();
i would be tempted to pull each of these major pieces of logic into a helper function within `completion.ts`:

* `commandCompletions`?
* `optionCompletions`?
* `customCompletions`?

2021-02-15 20:30 UTC, bcoe commented on lib/completion.ts
> +          if (negable)
It's this block especially where I think we'd benefit from a bit more decomposition. Could `completeOptionKey` could be pulled out to the top level of the file, along with us breaking apart `defaultCompletion` into a couple more helpers?

I think if we then add comments to each of the helpers, the completion logic might become easier to consume.

2021-02-15 20:30 UTC, bcoe commented on lib/completion.ts
> +function isFallbackCompletionFunction(
I like the use of type detection here 👍

2021-02-15 20:30 UTC, bcoe commented on lib/completion.ts
> +  return completionFunction.length > 3;
should this be `completionFunction.arguments.length` I'm surprised this worked.

2021-02-15 20:30 UTC, bcoe commented on test/completion.cjs
> +      checkUsage(
tests read quite well 👍

2021-02-16 22:29 UTC, gardenappl commented
I tried splitting the code into multiple functions, but they required a lot of arguments and it didn't look good at all. So instead I spent some time refactoring the whole thing into a class.
I also fixed handling of short options in aliases (see changes in unit tests).

2021-02-16 22:33 UTC, gardenappl commented
I am still kinda bothered by the fact that the API itself is not very clean. Right now the behaviour of `completion(...)` depends on how many arguments the function accepts:
* 2 args = synchronous function or Promise function, can't call default
* 3 args = callback function, can't call default
* 4 args = callback function, can call default

But this means that if you want to call the default function then you have to use callbacks. I already mentioned this when I created the PR and would like to hear some feedback on that.

2021-02-17 01:16 UTC, bcoe approved these changes
I think pulling the logic into a class was a very good compromise... and approach we could perhaps use elsewhere in the codebase.

LGTM. I will merge and release to a `next` branch so that you can test.

2021-02-17 01:16 UTC, merged