fix: use prototype
yargs/yargs pull request #2165
Opened 2022-04-11 22:43 UTC by jly36963

Relates to: https://github.com/yargs/yargs/pull/2161#discussion_r847542318

2022-04-21 13:55 UTC, bcoe approved these changes

2022-04-21 14:02 UTC, bcoe requested changes
MDN suggests using `Object.hasOwn`, vs., `Object.hasOwnProperty`, or `Object.prototype.hasOwnProperty`:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwnProperty#using_hasownproperty_as_a_property_name

Should we go this route?

2022-04-21 16:42 UTC, jly36963 commented
@bcoe The second code block in the MDN fragment you linked recommends `Object.prototype.hasOwnProperty.call` as an acceptable alternative, and as @dhensby said, `Object.hasOwn` is a relatively new feature in Node.

2022-04-25 20:28 UTC, bcoe approved these changes

2022-04-25 20:29 UTC, bcoe commented
👏 works for me, I should have read when `hasOwn` was introduced.

2022-05-16 00:58 UTC, merged