chore: add failing test for parser configuration and completion
yargs/yargs pull request #2332
Opened 2023-05-09 22:16 UTC by AgentEnder

There is an incompatibility between the parser configuration options and the completion feature within yargs. Setting strip-dashed: true in the parser configuration causes the completion feature to fail.

This is because the completion feature relies on passing '--get-yargs-completions' verbatim to yargs. Within the [Completion class](https://github.com/yargs/yargs/blob/main/lib/completion.ts?rgh-link-date=2023-05-08T17%3A03%3A24Z), the completionKey is explicitly set to get-yargs-completions. Within the YargsInstance, we explicitly check the following condition: completionKey in argv, in this location: [main/lib/yargs-factory.ts#L2054](https://github.com/yargs/yargs/blob/main/lib/yargs-factory.ts?rgh-link-date=2023-05-08T17%3A03%3A24Z#L2054)

Since the argv has been parsed already at this point, the argument is now 'getYargsCompletions' instead of 'get-yargs-completions'. This causes the completion feature to never be called.

Fixes: #2330

2023-05-10 07:35 UTC, shadowspawn commented
Long story. This is not quite right, but works in simple cases. I think there are less code changes required.

The strip-dashed spelling appearing in the "aliases" is a bit of cheat, it only appears in the parse results and is not recognised on the command-line and does not match what is on the command-line.

I added some trace statements to double-check my expectations. (I have a `-d, --debug` boolean option in my test program.) 

At this original line:
```
      const requestCompletions = this.#completion!.completionKey in argv;
```

`argv` is the parse result from calling yargs-parser internally, so with default options:
```
$ node index.js --get-yargs-completions --debug
{
  argv: {
    _: [],
    'get-yargs-completions': true,
    getYargsCompletions: true,
    debug: true,
    d: true,
    '$0': 'index.js'
  }
}
```

To cope with the author changing the parser configuration, we need to be flexible about what the property got called in the parse results.

Later at this point:
```
        const completionArgs = args.slice(
           args.indexOf(`--${this.#completion!.completionKey}`) + 1
         );
```

`args` is the original command-line args like:
```
$ node index.js --get-yargs-completions --debug
{ args: [ '--get-yargs-completions', '--debug' ] }
```

Here, we still want to check for the original unaltered `this.#completion!.completionKey` no matter what "alias" we found in `argv`.  With `'strip-dashed': true` the new code looks for the stripped name and fails to remove the dashed argument.

So requestCompletions should stay just a boolean, and only that initial calculation changes. I think you can just change `.find()` to `.some()` to match the semantics. We don't care which variation was found.

2023-05-10 07:37 UTC, shadowspawn requested changes
See long comment! I think this is close, but doing too much.

2023-05-10 07:39 UTC, shadowspawn commented
> This is because the completion feature relies on passing '--get-yargs-completions' verbatim to yargs.

This assumption is ok. The cause of the bug you observed is that the option name got changed in the parse results by the parser configuration settings, and fooled yargs.

2023-05-11 06:18 UTC, shadowspawn approved these changes
Thanks @AgentEnder

2023-05-11 06:22 UTC, shadowspawn commented
Good description with the PR, and added a test covering multiple configurations. Nice work.

2023-05-11 12:57 UTC, AgentEnder commented
Thanks for the help @shadowspawn!

Once it is merged, do you know when the next release would be? I've admittedly not paid too much attention to the yargs release schedule in the past.

2023-05-13 22:50 UTC, shadowspawn commented
I am guessing next release  1-2 months after last release (which was 2023-04-27).

2024-07-26 04:01 UTC, AgentEnder commented
@shadowspawn apologies, just checking in as this has been approved for a year now. 

Anything external contributors can do to help keep things moving?

2024-07-26 06:23 UTC, shadowspawn commented
In limbo at the moment. I am not merging PR or attempting releases, as without a second active maintainer my own PRs are blocked on needing a review so I would be unable to fix problems if I broke something.

> Anything external contributors can do to help keep things moving?

After mainline is building (#2393), updating PR if needed to build cleanly would be useful. Nothing in meantime.

2024-07-26 11:40 UTC, AgentEnder commented
>  without a second active maintainer my own PRs are blocked on needing a review so I would be unable to fix problems if I broke something.

If you all are looking for another active maintainer I'd be happy to spend a few hours a week on the project, maybe we can set up a call at some point to discuss?

2024-08-16 09:04 UTC, shadowspawn commented
(Thanks for the offer @AgentEnder . Nothing in the short-term. I can't add maintainers, so no point talking with me at the moment. 😆  )

2025-04-11 19:06 UTC, bcoe commented
@AgentEnder bother you to rebase, I've been cleaning up a lot of old PRs in prep for a v18 of yargs.

2025-04-23 20:31 UTC, bcoe commented
@AgentEnder friendly nudge on this one. If you don't have time to revisit (this admittedly very old contribution, sorry) I will rebase and merge sometime soon (but it's probably easier for you to push a change).

2025-04-25 20:42 UTC, merged

2025-04-25 20:47 UTC, bcoe commented
@AgentEnder thank you for the contribution, it's now available at `npm i yargs@next`.